name: Trigger Railway Deploy

on:
  push:
    branches: [main2]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Railway
      run: |
        curl -X POST ${{ secrets.RAILWAY_DEPLOY_HOOK }}
